dist: trusty
sudo: required
language: node_js
node_js:
  - "7"
os:
  - linux
env:
  global:
    - DBUS_SESSION_BUS_ADDRESS=/dev/null
    - DISPLAY=:99.0
    - CHROME_BIN=chromium-browser
before_script:
  - sh -e /etc/init.d/xvfb start
install:
  - npm install
script:
  - npm run lint
  - ng test --single-run --code-coverage
  - npm run e2e
after_script:
  - "./node_modules/.bin/codeclimate-test-reporter < coverage/lcov.info"
  - "./node_modules/.bin/coveralls < coverage/lcov.info"
after_success:
  - bash <(curl -s https://codecov.io/bash)
